# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Practical Machine Learning
tagline:             With a Deep Learning Bias
url:                 https://evilwire.github.io/dnnbook
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Knight Fu
  url:               https://twitter.com/evilwire
  email:             knfu@mediamath.com

# Custom vars
version:             0.1.0
github:
  repo:              https://github.com/evilwire/dnnbook
